### ISSUE TITLE
Change `getItem`'s default to `undefined`

### ISSUE THREAD

**Issue by avi12** [wxt-dev/wxt#1005]
#### Is your feature request related to a bug?
N/A

### Feature request
Suppose I want to fetch multiple storage values, currently, it'll look like:
```ts
const [value1, value2] = await Promise.all([
  storage.getItem<Type1>("local:key1").then(val => val ?? "foo"),
  storage.getItem<Type2>("local:key2").then(val => val ?? "bar")
]);;
```
I prefer having this code instead:
```ts
const [value1 = "foo", value2 = "bar"] = await Promise.all([
  storage.getItem<Type1>("local:key1"),
  storage.getItem<Type2>("local:key2"),
]);
```
which can be achieved without triggering a TypeScript error by changing `null` to `undefined` in
https://github.com/wxt-dev/wxt/blob/e3f00d279781c03dfd0903b41aada100ae5b1d55/packages/wxt/src/storage.ts#L309

**Comment by aklinker1** [comment]
The storage API has a built-in way of providing default values.

```ts
const [value1, value2] = await Promise.all([
  storage.getItem<Type1>("local:key1", { fallback: "foo" }),
  storage.getItem<Type2>("local:key2", { fallback: "bar" }),
]);
```

The storage APIs were designed to feel similar to `localStorage`, which is why it currently returns `null` instead of `undefined`. At this point, it would be a pretty disruptive breaking change to make.

I'm not necessarily opposed to this, `undefined` does make sense in many ways, but this would be really annoying to migrate to. So many little edge cases and checks (like someone accidentally used `=== null` insetad of `== null`, etc).

**Comment by avi12** [comment]
Huh, I was not ware of the `{ fallback: ... }` second argument

**Comment by avi12** [comment]
But does it actually affect `getItem`'s return type to get rid of `null`?

**Comment by baraich** [comment]
@avi12, I have fixed the type issue and made the pull request ([9516324](https://github.com/baraich/wxt/commit/95163243d3b768670cb84a110804d68cd6ac8669)) and once merged the issue would resolved in production.
