### ISSUE TITLE
Bump Vite version

### ISSUE THREAD

**Issue by aryzing** [wxt-dev/wxt#1015]
### Feature Request

Vite's latest is `5.4.8`, WXT using `5.3.5`.

#### Is your feature request related to a bug?

There's a type incompatibility for ESBuild plugins such as 

```ts
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill';

// ...

export default defineConfig({
  // ...
  vite: () =>
    defineViteConfig({
      optimizeDeps: {
        esbuildOptions: {
          plugins: [
            // @ts-expect-error - There seems to be an issue with the types of
            // the version of Vite used by WXT.
            NodeGlobalsPolyfillPlugin({
              buffer: true,
              process: true,
            }),
          ],
        },
      },
    }),
});
```

### What are the alternatives?

Using @ts-expect-error

**Comment by aiktb** [comment]
Not sure if it's related, I put two projects of wxt and remix in a pnpm repo, and since remix needs to use vite, and pnpm doesn't have dependency hoist, so I installed vite directly in devDeps.

Whenever I installed a different version of vite than wxt depends on, the types in vite.config.ts would be broken, my usecase is `build.css.postcss`.

I now use a normal postcss.config.js to avoid this.

**Comment by 1natsu172** [comment]
@aryzing To begin with, wxt can use `5.4.8` in semver way. And what are you using for your package manager? pnpm often breaks rollup peer dependencies lol.

![image](https://github.com/user-attachments/assets/897875e8-eebd-42a1-b9c5-a3ef6dff222a)

All I know is to run either of those two to repair the lockfile 

- `pnpm i --resolution-only`
- `pnpm i --fix-lockfile`

and then re-install(`pnpm i`).

(cc: @aiktb)

**Comment by Timeraa** [comment]
For these kinds of inconsistencies I just overwrite the version of `vite` in the package.json since they are so tightly coupled a lot of the times

**Comment by aklinker1** [comment]
I'm gonna close this since it's unrelated to WXT, more an issue with rollup subdepednencies and PNPM.

But yeah, if you want to upgrade Vite, but not list it in your package.json:

```sh
pnpm i vite@latest # or whatever version you need
pnpm rm vite
pnpm i --fix-lockfile
```

You may be able to just do `pnpm upgrade vite` instead of adding and removing it, but I don't know if that works on subdependencies.
