### ISSUE TITLE
Running tests using Bun fails

### ISSUE THREAD

**Issue by kelvinkipruto** [wxt-dev/wxt#1150]
### Describe the bug

When running tests using `bun`, they fail with the following error:
```
if (!(globalThis.chrome && globalThis.chrome.runtime && globalThis.chrome.runtime.id)) {
 throw new Error("This script should only be loaded in a browser extension.");
error: This script should only be loaded in a browser extension.
```

However when using any other package manager like `pnpm`, the tests pass

### Reproduction

[bun-test.zip](https://github.com/user-attachments/files/17677915/bun-test.zip)

### Steps to reproduce

Run `bun install` then `bun test`

### System Info

```shell
System:
    OS: macOS 15.0.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 68.67 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - /etc/profiles/per-user/kelvinkipruto/bin/node
    npm: 10.8.2 - /etc/profiles/per-user/kelvinkipruto/bin/npm
    pnpm: 9.10.0 - /etc/profiles/per-user/kelvinkipruto/bin/pnpm
    bun: 1.1.29 - /etc/profiles/per-user/kelvinkipruto/bin/bun
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 18.0.1
  npmPackages:
    wxt: ^0.19.13 => 0.19.13
```

### Used Package Manager

bun

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Repro failed for PNPM as well, you're using typescript syntax inside a `.js` file:

<img width="435" alt="Screenshot 2024-11-21 at 11 37 43 AM" src="https://github.com/user-attachments/assets/555224cc-efd6-446c-8d0b-b1d80ad6d55c">

After removing that, `pnpm test` passed like you said

`bun test` fails, but `bun run test` passes. This is because `bun test` doesn't run the `test` script defined in your `package.json`, it runs it's own test runner, which isn't vitest. 

https://bun.sh/docs/cli/test

So use `bun run test` to run vitest, don't use `bun test`.
