### ISSUE TITLE
MaxListenersExceededWarning when having 11+ content scripts defined

### ISSUE THREAD

**Issue by vladgabriel** [wxt-dev/wxt#1204]
### Describe the bug

When adding over 11 content scripts the following error is displayed:
```
(node:38511) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
```

### Reproduction

[memory-setup.zip](https://github.com/user-attachments/files/17903263/memory-setup.zip)

### Steps to reproduce

Run `yarn install` and `yarn dev`

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 76.14 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.asdf/installs/nodejs/20.15.1/bin/node
    Yarn: 4.5.0 - ~/.asdf/installs/nodejs/20.15.1/bin/yarn
    npm: 10.7.0 - ~/.asdf/plugins/nodejs/shims/npm
    bun: 1.0.26 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.86
    Chrome Canary: 133.0.6858.0
    Safari: 17.2.1
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
I've noticed this as well, seems like each entrypoint group (build step) adds a listener... I assume because vite is adding it? Not 100% sure which dependency is causing it, but vite is my best guess.

**Comment by aklinker1** [comment]
This is caused by:

https://github.com/wxt-dev/wxt/blob/5a3790a7d3595b7b44cf1824c569b379485536dd/packages/wxt/src/core/utils/building/find-entrypoints.ts#L360-L361

Specifically when importing multiple entrypoints to extract their options during the build process, like content script `matches`, we use `vite-node` to import the TS file and do some preprocessing to speed things up.

However, for every imported entrypoint, we have to create a Vite dev server, and that's where the warning comes from, the dev server setting up a listener to close the server when stopping the process. 

Fix is simple, only create a single dev server when importing entrypoint files, but refactoring the code to support that won't be... An easier fix is to import the files one by one, not in parallel, or setup a queue that only allows 9 imports be running at a time.

But I'd rather refactor and get this done right. For now, you can ignore this error. It shouldn't be causing any problems.
