### ISSUE TITLE
webextension-polyfill incompatible with Manifest v3

### ISSUE THREAD

**Issue by dvlden** [wxt-dev/wxt#224]
I believe that polyfill is injected by wxt at all times, even when manifest v3 is used for build?
Correct me if I am wrong, but polyfill should not exist for manifest v3.

Perhaps this is all that's needed:
[https://github.com/mozilla/webextension-polyfill/issues/329#issuecomment-1594562103](https://github.com/mozilla/webextension-polyfill/issues/329#issuecomment-1594562103)

Aside, I'm having issues using `browser.browserAction.setIcon()` and `browser.browserAction.setBadgeText()` because on manifest v3, that's no longer correct API. It's now `browser.action`. If I have to create some of these fallbacks, then I think `webextension-polyfill` is useless for everything, except types. But then, we have chrome types here as an alternative: [https://www.npmjs.com/package/@types/chrome](https://www.npmjs.com/package/@types/chrome)

So perhaps you can make interface to match `browser` to be exact as `chrome`.

I'd love the option to opt-out of webextension-polyfill, so that I can create my own tiny wrapper, unless you see my point here, or unless I'm wrong and there's something that has to be enabled/disabled to make this work as expected?

Aside, how do I change manifest v2 to v3 for Firefox, because I want to test what may or may not work?

**Comment by dvlden** [comment]
To answer some of these questions for myself and for the others, to create a different manifest build, just pass `--mv3` to the build or dev commands.

The `--mv3` will not change `service_worker` to `scripts` for Firefox browser. So it can't work as expected.

Still not sure how to get around all of it.

**Comment by aklinker1** [comment]
> Correct me if I am wrong, but polyfill should not exist for manifest v3.

For the most part, you're correct. The polyfill is basically a noop for Chrome MV3 extensions, just like any other polyfill that is injected into a environment where it's not needed.

However, as a framework that supports more than just Chrome MV3 (Firefox MV2 and legacy Chrome MV2), WXT will not be dropping the polyfill until:

1. Firefox releases MV3 support, which currently expiremental, and
2. Google officially kills MV2

Even after Firefox supports MV3, [they've pledged to keep some of the MV2 APIs ad-blockers use](https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/), among other changes. This means that Chrome and Firefox will never be the same, and as developers, we will always have to do some form of feature detection.

> `webextension-polyfill` incompatible with Manifest v3

This is just not true. It is 100% compatible with MV3. Including the polyfill does not break any of chrome's APIs. It just may not behave the way you expect it to.

The polyfill provides a standardized, promise-based API that works on all browsers and all manifest versions, _**where possible**_. It cannot magically resolve breaking changes between manifest versions, like determining if it should call `browser.pageAction` or `browser.browserAction` for MV2 when calling `browser.action`. There will always be an edge case were it gets it wrong, so it's easier to make the develper implement feature detection.

> [!NOTE]
> These APIs are mostly identical, so you can use use `await (browser.action ?? browser.pageAction).setIcon(...)` as a quick work around for one-off function calls. If the API is not available for both manifest versions, typescript will report a type error.

Since WXT needs to support all browsers and all manifest versions, including combinations you may not be using, WXT will continue to use `webextension-polyfill` internally, and it will continue to add the polyfill to content scripts and any other entrypoints where you use `wxt/browser`.

But like I said in another post, you don't have to use the `browser` variable WXT provides. You can use `chrome` and install the types you mentioned. If you're concerned about the additional size that `webextension-polyfill` takes up in the production bundle (40 kb per entrypoint), you can tell Vite to resolve it to a custom module you provide.

> [!WARNING]
> This is a hack and I make no promises to support it.

```ts
// wxt.config.ts
import { defineConfig } from 'wxt';
import path from 'node:path';

export default defineConfig({
  vite: () => ({
    resolve: {
      alias: {
        '^webextension-polyfill$': path.resolve("chrome.js")
      },
    },
  }),
});
```

```js
// chrome.js
export default chrome
```

**Comment by aklinker1** [comment]
> The `--mv3` will not change `service_worker` to `scripts` for Firefox browser. So it can't work as expected.

I don't understand the issue here. `wxt build -b firefox` should use `service_worker` for the background.

`wxt build -b firefox` and `wxt build -b firefox --mv2` will use `scripts` for the background.

I'm 99% sure I have E2E tests that cover this behavior, and I know it works like this for several of my own extensions that target Firefox MV2

**Comment by dvlden** [comment]
Thank you for your input! 
I'll check this out today and see where it leads me. 

Polyfill is compatible between browers, but what you said... Doesn't cover differences between MV2 and MV3. Which for my case, I think, would be only what I mentioned in this issue.

---

It's not abound 40kb additional size per entry, but more of why would I ship it, if it isn't needed.

I'll try that Vite approach you gave me, and see how it goes. For my case, MV3 will work for Firefox too, with the exception of `service_worker` not being supported.

What I meant by `--mv3` flag not working when passing it to build option as `-b firefox --mv3` is that it doesn't care that the target is Firefox and keeps using `background.service_worker` instead of `background.scripts[]`. 

I understand that most extensions will benefit from WXT having `webextension-polyfill` as batteries included, but I wonder why wouldn't you consider making it possible to opt-out by configuration?

**Comment by aklinker1** [comment]
> What I meant by --mv3 flag not working when passing it to build option as -b firefox --mv3 is that it doesn't care that the target is Firefox and keeps using background.service_worker instead of background.scripts[].

I was still confused by this, because my understanding was that Firefox requires `backgroumd.service_worker` for MV3, just like chrome and Safari.

But after reading [Mozilla's docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts) again, that doesn't seem to be true...

It appears Firefox requires you to use `scripts` or `page` for MV3, making sure to set `persistent: false`... Is that true?

I haven't actually tried running a MV3 extension on Firefox before, I'll give it a go today and fix this if true.

> I understand that most extensions will benefit from WXT having webextension-polyfill as batteries included, but I wonder why wouldn't you consider making it possible to opt-out by configuration?

Because the polyfill is essential for the internal logic in dev mode and it is essential for the internal logic for managing the lifecycle of content scripts in production. I'm not 100% convinced that removing it will not break anything.

If the hack works for you, let me know. I will consider adding an `experimental.webextensionPolyfill` option that applies this patch when set to false. But even when set to false, it would still be included in dev mode or if the target is Firefox or if the target is MV2 (times when the polyfill is required). I also need to consider how Safari will best work, Safari is weird and different.

**Comment by dvlden** [comment]
Hahah I had a great laugh reading your comment with multiple edits... 🤣 
I tried the Vite setting you gave me, but apparently it did nothing regarding exclusion of polyfill or I failed to do it properly.

Regarding Firefox, I tried my base of extension built with `--mv3` and it shows up error.

`{ service_worker: 'background.js' }` must be replaced with `{ scripts: ['background.js'] }` and `persistant` flag must not exist. [Scroll to Event-driven background scripts section](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/)

---

Happy to hear that you will implement an experimental feature flag. Aside, I tried making a sample with Vite (without WXT) to see if I will have everything cross-browser compatible without polyfill and I have no issues at all.

Here's my attempt, so it may help with the feature flag thingy...

> **package.json**
```json
{
  "devDependencies": {
    "chrome-types": "^0.1.241",
  }
}
```

> **src/shims.d.ts**
```ts
export {}

declare global {
  declare var browser: typeof chrome
}
```

> **src/background.ts** _(for example)_
```ts
if (!('browser' in globalThis)) {
  browser = chrome
}

;(async () => {
  // Because I have hard times enabling top-level await
  console.log(browser)
})()
```

Judging by WXT's implementation of how `webextension-polyfill` is automatically injected in each input that uses it, I assume there's a magic trick with Vite, I'm not aware of that could be used to add that condition on top of every input? Feel free to reveal your magic to me, I'd be happy to learn.

**Comment by aklinker1** [comment]
> https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/

Ok, wow, firefox's MV3 support is already out? I did not know that... It also looks like Firefox 105  and above will be compatible for the most part, and Firefox 109 and above will be 100% compatible. Both have been out for a while, long enough that most users are above those versions.

Ok, so now I understand more context around this issue. For now, I'm gonna stick with an experimental flag. I need to spend some time making sure Safari is compatible as well.

**Comment by aklinker1** [comment]
> Feel free to reveal your magic to me, I'd be happy to learn.

The magic comes from 2 things: [`unimport`](https://github.com/unjs/unimport) and [Vite's virtual modules](https://vitejs.dev/guide/api-plugin.html#virtual-modules-convention).

### Unimport

`unimport` is configured so that anytime you use the `browser` variable, it imports `wxt/browser`:
https://github.com/wxt-dev/wxt/blob/421c0e412d9a36316079b2e7593bfbb38acb20f5/src/core/utils/unimport.ts#L18

Which simply imports the polyfill. 
https://github.com/wxt-dev/wxt/blob/421c0e412d9a36316079b2e7593bfbb38acb20f5/src/browser.ts#L4

At build time, unimport does not know that `browser` may already exist at runtime, so it adds the import at the top of all your files during the build process.

### Virtual Modules

Instead passing your `entrypoints/*.ts` files into Vite to build, WXT uses it's own "virtual entrypoints" when bundling the TS file.
https://github.com/wxt-dev/wxt/blob/421c0e412d9a36316079b2e7593bfbb38acb20f5/src/core/utils/building/build-entrypoints.ts#L56-L63

So here, if the entrypoint needs to be virtualized, like a content script, instead of building `/path/to/entrypoints/content.ts`, it tells Vite to build `virtual:wxt-content-script?/path/to/entrypoints/content.ts`. There's nothing special about this string yet. By default, Vite would look for a node module with that name, notice it doesn't exist, and throw a build error. We need to tell Vite that when it sees this string, it should use WXT's entrypoint. We do that in a Vite plugin:

https://github.com/wxt-dev/wxt/blob/421c0e412d9a36316079b2e7593bfbb38acb20f5/src/core/vite-plugins/virtualEntrypoint.ts#L14-L41

This plugin basically says: When you see a virtual entrypoint, use one of these files:

- [`wxt/src/virtual/background-entrypoint.ts`](https://github.com/wxt-dev/wxt/blob/421c0e412d9a36316079b2e7593bfbb38acb20f5/src/virtual/background-entrypoint.ts) (imports `webextension-polyfill`)
- [`wxt/src/virtual/content-script-entrypoint.ts`](https://github.com/wxt-dev/wxt/blob/421c0e412d9a36316079b2e7593bfbb38acb20f5/src/virtual/content-script-entrypoint.ts) (imports `webextension-polyfill`)
- [`wxt/src/virtual/unlisted-script-entrypoint.ts`](https://github.com/wxt-dev/wxt/blob/421c0e412d9a36316079b2e7593bfbb38acb20f5/src/virtual/unlisted-script-entrypoint.ts)

The content script virtual entrypoint is a good example of this:

https://github.com/wxt-dev/wxt/blob/421c0e412d9a36316079b2e7593bfbb38acb20f5/src/virtual/content-script-entrypoint.ts#L1-L17

It does several things:

1. Import another virtual module, `virtual:user-content-script`, on line 1
2. Creates the content script context variable
3. Calls the `main` function from the content script definition.

`virtual:user-content-script` is another virtual entrypoint, but instead of using a custom `resolveId` function like we did before, the plugin from above just does a find/replace to tell it to import your file instead.

https://github.com/wxt-dev/wxt/blob/421c0e412d9a36316079b2e7593bfbb38acb20f5/src/core/vite-plugins/virtualEntrypoint.ts#L39

**Comment by dvlden** [comment]
Hot damn, this is amazing. Thank you for your time and effort trying to explain all this to me. Much appreciated!

**Comment by dvlden** [comment]
I'm unsure if I am doing something wrong here.

- [x] experimental feature set in the config
```
// wxt.config.ts
experimental: {
  includeBrowserPolyfill: false,
}
```

- [x] alias added
```ts
// wxt.config.ts
vite: () => ({
  resolve: {
    alias: {
      'webextension-polyfill': 'polyfill.js',
    },
  },
}
```

- [x] polyfill.js created
```
export default chrome
```

Also tried this, as I used it elsewhere and doesn't work:
```
if (!('browser' in globalThis)) {
  globalThis.browser = chrome
}

const browser = globalThis.browser
export default browser
```

<img width="1165" alt="Screenshot 2023-11-13 at 19 52 50" src="https://github.com/wxt-dev/wxt/assets/3460368/ca545d40-7df5-4e80-892d-e7e8bbed3f4d">

**Comment by dvlden** [comment]
Okay, figured it out. So these two things are for two different purposes.

1. Using alias in Vite's config, will use my custom polyfill wherever `webextension-polyfill` was meant to be used.

2. Using `experimental` feature flag, will omit the `webextension-polyfill` entirely from the output.

Both can't be used at the same time and shouldn't be used. It's either one or the other, correct?

Since I'm building cross-browser extension, my tiny polyfill for MV3 only support - makese sense to me. Please fill me up if I am wrong.

**Comment by aklinker1** [comment]
Yup, you don't need to do anything except for setting the experimental flag. It's setting up the alias and chrome export behind the scenes for you.
