### ISSUE TITLE
Docs on the recommended approach for using UI elements such as panels in devtools entrypoints

### ISSUE THREAD

**Issue by AndrewWalsh** [wxt-dev/wxt#305]
### Feature Request

This page describes the setup of a devtools entrypoint https://wxt.dev/entrypoints/devtools.html.

Devtools pages can have UI elements, such as panels https://developer.chrome.com/docs/extensions/how-to/devtools/extend-devtools#devtools-ui

What is the recommended way of creating a panel or UI element in a devtools entrypoint with `wxt`?

#### Is your feature request related to a bug?

No

### What are the alternatives?

N/a

### Additional context

N/a

**Comment by aklinker1** [comment]
@AndrewWalsh I've never created a devtools extension before, so I can only guess.

Do you call `chrome.devtools.panels.create` or `chrome.devtools.panels.elements.createSidebarPane`? Inside your background script or inside your `devtools_page`? I assume `devtools_page` because it says the `chrome.devtools` API is only available inside it? If that's the case, I'd recommend creating the following setup:

```
entrypoints/
  devtools/
    index.html
    main.ts              - call "chrome.devtool" APIs in this file to register your panels/panes
  devtools-panel-name/
    index.html           - Load this file with "chrome.devtools.panels.create"
    ...
  devtools-pane-name/
    index.html           - Load this file with "chrome.devtools.panels.elements.createSidebarPane"/"setPage"
    ...
```

This makes sure your custom panels and panes are bundled as unlisted pages accessible at runtime.

Are you familiar with the devtools API? If so, does that all make sense to you? If not, I'll look into it soon and provide better guidance. Once I know how to do all this, I'll update the docs with the recommended approach.

**Comment by AndrewWalsh** [comment]
That makes complete sense, thank you for the guidance.

**Comment by aklinker1** [comment]
@AndrewWalsh I've added an example and improved the entrypoint docs based on what I shared above.
