### ISSUE TITLE
 Invalid value for 'web_accessible_resources[1]'. Invalid match pattern.

### ISSUE THREAD

**Issue by yunsii** [wxt-dev/wxt#329]
### Describe the bug

- `defineContentScript` with matches like `https://docs.google.com/docuemnt/*`
- It generate css `web_accessible_resources` with the same matches

It break the rule https://developer.chrome.com/docs/extensions/reference/manifest/web-accessible-resources#manifest_declaration
![image](https://github.com/wxt-dev/wxt/assets/18096089/cfd3bbba-57cb-4ae7-bcce-51ff260bfd83)

### To Reproduce

https://github.com/yunsii/browser-extension-with-fasttext.wasm.js

*Placeholder only, reproduction is not necessary*

### Expected behavior

Load content css correctly.

**Comment by aklinker1** [comment]
> Reproduction is not necessary

Reproductions are always necessary. Why? Here's a good post: https://antfu.me/posts/why-reproductions-are-required

Specifically, if someone other than I looked at this, they might struggle to create their own reproduction, because they may not know that `web_accessible_resources` entries are only generated when the `cssInjectionMode` has be set. You don't call that out, but a reproduction would make that case clear.

It's fine this time, but in the future, please at least provide a minimal project ZIP file or failing test case to help the maintainers out.

**Comment by aklinker1** [comment]
Fix release in [`v0.13.5`](https://github.com/wxt-dev/wxt/releases/tag/v0.13.5)

**Comment by yunsii** [comment]
> > Reproduction is not necessary
> 
> Reproductions are always necessary. Why? Here's a good post: https://antfu.me/posts/why-reproductions-are-required
> 
> Specifically, if someone other than I looked at this, they might struggle to create their own reproduction, because they may not know that `web_accessible_resources` entries are only generated when the `cssInjectionMode` has be set. You don't call that out, but a reproduction would make that case clear.
> 
> It's fine this time, but in the future, please at least provide a minimal project ZIP file or failing test case to help the maintainers out.

Thanks for your patient explanation, I will pay attention next time.

**Comment by aklinker1** [comment]
No worries! Thanks for opening the issue 🙂
