### ISSUE TITLE
How to use createIframeUi with Vue?

### ISSUE THREAD

**Issue by neilfranci** [wxt-dev/wxt#341]
### Describe the bug

I'm trying to mount a .vue to createIframeUi, but I can't find any example with content script.

#### To Reproduce
Share minimal reproduction. Examples of a minimal reproduction:
[learn-wxt.zip](https://github.com/wxt-dev/wxt/files/13914056/learn-wxt.zip)

Steps to reproduce the bug using the reproduction:

1. Install dependencies: `pnpm i`
2. Start dev mode: `pnpm dev`

### Expected behavior

The Content.vue should be under entry.html div with the id="app"
but none showing up

### Screenshots

![image](https://github.com/wxt-dev/wxt/assets/66520542/35ab1bbe-9550-4a6b-8b46-a991a0f248e9)

### Environment

```
 System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 4.23 GB / 15.73 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.121)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    wxt: ^0.14.0 => 0.14.0
```

### Additional context

> I would love an example content script with different modes in different frameworks.
> It will help people come along with the framework.
> 
> and the documentation is a bit limited.

### Thank you for the framework! I love it so much!

**Comment by aklinker1** [comment]
To use a vue app with `createIframeUi`, the vue app should be created inside the iframe, not inside the content script.

The reason why there are framework examples for all the major frameworks for `createIntegratedUi` and `createShadowRootUi` are because they're non-standard. But `createIframeUi` just loads an HTML page in an iframe, nothing special there.

For example, in the ZIP you shared, just load the popup in the iframe instead of your custom HTML file, and it works. You just need to mimic the popup's setup for your custom UI.

```ts
const ui = createIframeUi(ctx, {
  position: "overlay",
  page: "/popup.html",
});
```

And don't forget to update your manifest:

```ts
    web_accessible_resources: [
      {
        resources: ["popup.html"],
        matches: ["<all_urls>"],
      },
    ],
```

And it works as expected.

[working-iframe.zip](https://github.com/wxt-dev/wxt/files/13914832/working-iframe.zip)

> Thank you for the framework! I love it so much!

😄 Thanks!
