### ISSUE TITLE
Firefox has `window.chrome` defined

### ISSUE THREAD

**Issue by dvlden** [wxt-dev/wxt#376]
### Describe the bug

Firefox should not have `window.chrome` defined. I am creating a feature and I am using a simple conditional `typeof chrome !== 'undefined'` to make a different thing for Firefox. It fails, because `window.chrome` is identical to `window.browser` when I type it inside of extension debugger.

### To Reproduce

Make a fresh WXT project and then follow the steps below.

1. Install dependencies: `pnpm i`
2. Build the extension for Firefox: `pnpm run build:firefox`
3. Load extension in Firefox
4. Open console to debug the popup interface
5. Type `window.chrome`

### Expected behavior

`window.chrome` should be `undefined`

### Screenshots

**WXT**
<img width="616" alt="Screenshot 2024-01-27 at 16 10 21" src="https://github.com/wxt-dev/wxt/assets/3460368/2a56e820-4e22-48ab-84a2-9ab608a90b68">

**Firefox extension example (Beastify)**
<img width="616" alt="Screenshot 2024-01-27 at 16 15 25" src="https://github.com/wxt-dev/wxt/assets/3460368/e86c5bba-0ab8-459a-9596-e35db1392a99">

### Environment

```
  System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 60.14 GB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - ~/.asdf/installs/nodejs/21.2.0/bin/node
    npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.14.3 - /opt/homebrew/bin/pnpm
    bun: 1.0.21 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 121.1.62.153
    Chrome: 121.0.6167.85
    Edge: 121.0.2277.83
    Firefox Nightly: 124.0a1
    Safari: 17.2.1
    Safari Technology Preview: 17.4
  npmPackages:
    wxt: ^0.14.0 => 0.14.6
```

### Additional context

At first, I thought it somehow could be my own custom browser polyfill that we discussed not long ago in some other issue. But I tried removing my polyfill and I still get the same outcome. I even tried enabling experimental feature, that excludes browser polyfill altogether and I still get `window.chrome` as defined. So this doesn't help either...

```ts
// wxt.config.ts
experimental: {
  includeBrowserPolyfill: false,
}
```

I am not sure what is defining window.chrome for Firefox, but I do not want that. Please help!

**Comment by aklinker1** [comment]
Whats the problem here? Firefox includes the `chrome` global for compatibility. I think you're the one who told me about that while trying to convince me to get rid of the polyfill... So of course `window.chrome` exists. Not sure why you're seeing the behavior in Beastify.

<img width="945" alt="Screenshot 2024-01-27 at 10 21 42 AM" src="https://github.com/wxt-dev/wxt/assets/10101283/605ff8b6-a989-4b27-b56b-ffcb4515ec9e">

If you want to check which browser the build was targeting, you can use the `__BROWSER__` or `__IS_FIREFOX__` global. It's undocumented, but it's there, along with several other globals: https://github.com/wxt-dev/wxt/blob/35865adcb256a685761a99df2684bdf8712c7486/src/core/utils/globals.ts

```ts
if (__IS_FIREFOX__) {
  // ...
}

// or

if (__BROWSER__ === "firefox") {
  // ...
}
```

I'll add some docs about these. I haven't documented them yet because I'm considering moving them into `import.meta.env.isFirefox`, but they're here to stay in one form or another.

**Comment by aklinker1** [comment]
I've added docs, see https://wxt.dev/guide/multiple-browsers.html#runtime

**Comment by dvlden** [comment]
Oh lovely. Did not know about those magic constants. 
Would love to see them in `import.meta.env` at some point for sure. Will use them now in a shape that they exist. 

Thanks!
