### ISSUE TITLE
How to open sidepanel when click the plugin icon in chrome?

### ISSUE THREAD

**Issue by zeroxer** [wxt-dev/wxt#570]

**Comment by aklinker1** [comment]
1. Add an on click listener to your action
   https://developer.chrome.com/docs/extensions/reference/api/action#event-onClicked

2. Call `open`
   https://developer.chrome.com/docs/extensions/reference/api/sidePanel#method-open

```ts
browser.action.onClicked.addListener(() => browser.sidePanel.open());
```

**Comment by abegehr** [comment]
I ran into the same question. Two remarks:
1. Make sure your `action` object in manifest does not have a `default_popup` field set, otherwise `action.onClicked` will not be called.
2. The `browser` [extension api](https://wxt.dev/guide/extension-apis.html#extension-apis) does not include `sidePanel`, so TS will complain ("Property 'sidePanel' does not exist on type 'AugmentedBrowser'"), however it still works. I've opened an issue [here](https://github.com/mozilla/webextension-polyfill/issues/583).

**Comment by abegehr** [comment]
Instead of using the `onClicked` handler, this is the way to do it from the chrome docs: https://developer.chrome.com/docs/extensions/reference/api/sidePanel#open-action-icon

```
// Allows users to open the side panel by clicking on the action toolbar icon
browser.sidePanel
  .setPanelBehavior({ openPanelOnActionClick: true })
  .catch((error) => console.error(error));
```

**Comment by cloudflypeng** [comment]
and make sure you add 
<img width="315" alt="image" src="https://github.com/wxt-dev/wxt/assets/44285412/2152ff9e-4c53-4e8a-b476-4428ff36ccc9">
into wxt.config.ts because it's not auto

**Comment by aklinker1** [comment]
`v0.18.2` adds the permission automatically when a side panel entry point is defined

**Comment by nileshtrivedi** [comment]
@aklinker1 Thoughts on adding a sidepanel page by default in all templates?

**Comment by aklinker1** [comment]
I've consistently said no to adding content to the templates:

- https://github.com/wxt-dev/wxt/issues/552
- https://github.com/wxt-dev/wxt/issues/325
- https://github.com/wxt-dev/wxt/issues/369
- https://github.com/wxt-dev/wxt/issues/187

So I'm going to say no to this one as well. Templates are a huge time sink to keep up to date and the more features/variants that are added, the more time it takes away from me to add features and fixes to WXT itself.

That said, I'm open to adding community template support to the `init` command!
