### ISSUE TITLE
declarativeContent doesn't have a Typescript type defined

### ISSUE THREAD

**Issue by kevincam3** [wxt-dev/wxt#660]
### Describe the bug
When trying to use browser.declarativeContent my IDE (PhpStorm) displays it in red to signal that it's not recognized.

Same as above

### To Reproduce
type: browser.declarativeContent in your IDE

Share minimal reproduction. Examples of a minimal reproduction:
![image](https://github.com/wxt-dev/wxt/assets/870934/21fa5f02-46fd-46fb-a4e1-0f32febe5517)

**Comment by aklinker1** [comment]
Types are provided by [`webextension-polyfill-ts`](https://github.com/Lusito/webextension-polyfill-ts). I've attempted to reach out and ask if I could help maintain and release changes, but didn't get a response... I would like to update the types since chrome has been adding more APIs with MV3, but don't have the time.

Maybe it's time to move on from the polyfill and use `chrome` and https://www.npmjs.com/package/@types/chrome instead... Not sure if these types support cross-platform APIs, but the package is better maintained. But IMO the polyfill is still necessary, so I'm hesitant to switch from it.

**Comment by kevincam3** [comment]
It looks like they claim that these types are auto generateed. So I submitted an issue about this over there as well. Maybe somebody will up date it.

**Comment by aklinker1** [comment]
🤞 Thanks!

**Comment by aklinker1** [comment]
Just released an experiment feature in `wxt@0.19` to switch to `@types/chrome`, which has this type in it. Try it out and let me know how it goes:

https://github.com/wxt-dev/wxt/issues/868
