### ISSUE TITLE
I did not find any relevant statements about the DesktopCapture API in the declaration file, which is part of the Google Extension API

### ISSUE THREAD

**Issue by message163** [wxt-dev/wxt#680]
### Describe the bug

I did not find any relevant statements about the DesktopCapture API in the declaration file, which is part of the Google Extension API

### To Reproduce

   browser.desktopCapture.chooseDesktopMedia(["window","screen","tab"],tab, (streamId:string) => {
              console.log(streamId)
        })

![image](https://github.com/wxt-dev/wxt/assets/32630999/ef1f5518-05bf-413f-833e-1c77cb3dd901)

**Comment by aklinker1** [comment]
This is a non-standard API only chrome supports, so it is not typed. I'm considering adding types for these anyways, but haven't yet because the goal of WXT is to promote cross-browser development.

**Comment by message163** [comment]
If allowed, I can contribute this part of the declaration code

**Comment by aklinker1** [comment]
@message163 please do! Might be hard because of the way `@types/webextension-polyfill` and `@types/chrome` use namespaces... But ideally we just add any types we need from `@types/chrome` into the existing `AugmentedBrowser` types.

https://github.com/wxt-dev/wxt/blob/main/packages%2Fwxt%2Fsrc%2Fbrowser.ts#L6-L9

**Comment by aklinker1** [comment]
Just released an experiment feature in `wxt@0.19` to switch to `@types/chrome`, which has this type in it. Try it out and let me know how it goes:

https://github.com/wxt-dev/wxt/issues/868
